	export const cards = {
		1 : {id:1, value: 10, points: 11, seed: "denari", name: "asso"},
		2 : {id:2, value: 1, points: 0, seed: "denari", name: "due"},
		3 : {id:3, value: 9, points: 10, seed: "denari", name: "tre"},
		4 : {id:4, value: 2, points: 0, seed: "denari", name: "quattro"},
		5 : {id:5, value: 3, points: 0, seed: "denari", name: "cinque"},
		6 : {id:6, value: 4, points: 0, seed: "denari", name: "sei"},
		7 : {id:7, value: 5, points: 0, seed: "denari", name: "sette"},
		8 : {id:8, value: 6, points: 2, seed: "denari", name: "donna"},
		9 : {id:9, value: 7, points: 3, seed: "denari", name: "cavallo"},
		10 : {id:10, value: 8, points: 4, seed: "denari", name: "re"},

		11 : {id:11, value: 10, points: 11, seed: "spade", name: "asso"},
		12 : {id:12, value: 1, points: 0, seed: "spade", name: "due"},
		13 : {id:13, value: 9, points: 10, seed: "spade", name: "tre"},
		14 : {id:14, value: 2, points: 0, seed: "spade", name: "quattro"},
		15 : {id:15, value: 3, points: 0, seed: "spade", name: "cinque"},
		16 : {id:16, value: 4, points: 0, seed: "spade", name: "sei"},
		17 : {id:17, value: 5, points: 0, seed: "spade", name: "sette"},
		18 : {id:18, value: 6, points: 2, seed: "spade", name: "donna"},
		19 : {id:19, value: 7, points: 3, seed: "spade", name: "cavallo"},
		20 : {id:20, value: 8, points: 4, seed: "spade", name: "re"},

		21 : {id:21, value: 10, points: 11, seed: "coppe", name: "asso"},
		22 : {id:22, value: 1, points: 0, seed: "coppe", name: "due"},
		23 : {id:23, value: 9, points: 10, seed: "coppe", name: "tre"},
		24 : {id:24, value: 2, points: 0, seed: "coppe", name: "quattro"},
		25 : {id:25, value: 3, points: 0, seed: "coppe", name: "cinque"},
		26 : {id:26, value: 4, points: 0, seed: "coppe", name: "sei"},
		27 : {id:27, value: 5, points: 0, seed: "coppe", name: "sette"},
		28 : {id:28, value: 6, points: 2, seed: "coppe", name: "donna"},
		29 : {id:29, value: 7, points: 3, seed: "coppe", name: "cavallo"},
		30 : {id:30, value: 8, points: 4, seed: "coppe", name: "re"},

		31 : {id:31, value: 10, points: 11, seed: "bastoni", name: "asso"},
		32 : {id:32, value: 1, points: 0, seed: "bastoni", name: "due"},
		33 : {id:33, value: 9, points: 10, seed: "bastoni", name: "tre"},
		34 : {id:34, value: 2, points: 0, seed: "bastoni", name: "quattro"},
		35 : {id:35, value: 3, points: 0, seed: "bastoni", name: "cinque"},
		36 : {id:36, value: 4, points: 0, seed: "bastoni", name: "sei"},
		37 : {id:37, value: 5, points: 0, seed: "bastoni", name: "sette"},
		38 : {id:38, value: 6, points: 2, seed: "bastoni", name: "donna"},
		39 : {id:39, value: 7, points: 3, seed: "bastoni", name: "cavallo"},
		40 : {id:40, value: 8, points: 4, seed: "bastoni", name: "re"}
	};
